### ISSUE TITLE
名前解決をOSに頼らずに実行したい

### ISSUE THREAD

**Issue by k4taya** [kitkatayama/godnsbl#1]
Go の `net.LookupHost` を使用しているが、これは実行するOSに依存する。
特に、OS上の名前解決が 8.8.8.8 などのパブリックDNSを使用している場合、DNSBLによっては、問い合わせを拒否することがある。

そのため、`net.Resolver` で、DNSBLのNSを名前解決先として直接指定することで、OSの名前解決に頼らず、実行主体の端末のみで名前解決を行う。

**Comment by k4taya** [comment]
## やりたいこと

調査するDNSBL(例: `zen.spamhaus.org` ) のNSを取得する

```
$ dig ns zen.spamhaus.org +noall +ans
zen.spamhaus.org.	2861	IN	NS	c.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	b.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	a.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	d.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	e.gns.spamhaus.org.
```

NSのAレコードを名前解決する

```
$ dig a c.gns.spamhaus.org +noall +ans
c.gns.spamhaus.org.	594	IN	A	52.193.25.66
```

NSのAレコードに対して、必要なIPアドレスの名前解決を行う

```
$ dig a 2.0.0.127.zen.spamhaus.org +noall +ans @52.193.25.66
2.0.0.127.zen.spamhaus.org. 60	IN	A	127.0.0.2
2.0.0.127.zen.spamhaus.org. 60	IN	A	127.0.0.10
2.0.0.127.zen.spamhaus.org. 60	IN	A	127.0.0.4
```

上記の内容を、 go で実現したい

**Comment by k4taya** [comment]
`/16` など結構大きめのネットワークを調べる場合、IPの数だけ問い合わせが発生する
なるべく負荷を分散させるため、問い合わせ先はラウンドロビンなどで分散する必要がある
尚、NSレコードと、NSレコードに登録されてるドメインのAレコードの2段階で分散があるので気を付ける

### NSレコード

```
$ dig ns zen.spamhaus.org +noall +ans
zen.spamhaus.org.	2861	IN	NS	c.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	b.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	a.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	d.gns.spamhaus.org.
zen.spamhaus.org.	2861	IN	NS	e.gns.spamhaus.org.
```

### NSレコードに登録されてるドメインのAレコード

```
$ dig a c.gns.spamhaus.org +noall +ans
c.gns.spamhaus.org.	594	IN	A	52.193.25.66
$ dig a d.gns.spamhaus.org +noall +ans
d.gns.spamhaus.org.	600	IN	A	195.123.241.139
d.gns.spamhaus.org.	600	IN	A	141.164.41.35
d.gns.spamhaus.org.	600	IN	A	52.79.110.70
...
```

**Comment by k4taya** [comment]
`miekg/dns` など大規模なものを導入しなくてよいので、候補はこのあたりでいいかな

- `os/exec` 
- DoH

**Comment by kitkatayama** [comment]
`miekg/dns` など大規模なものを導入しなくてよいので、候補はこのあたりでいいかな

- `os/exec` 
- DoH

**Comment by k4taya** [comment]
https://github.com/kitkatayama/godnsbl/commit/d2b33317c0389ea389979e031cbedff33c12affc で対応完了した。

https://github.com/kitkatayama/godnsbl/issues/1#issuecomment-1513529045

> 尚、NSレコードと、NSレコードに登録されてるドメインのAレコードの2段階で分散があるので気を付ける

ここについては、取得したNSレコードに沿ってラウンドロビンするように負荷分散する実装を入れた。
